"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useLayoutEffect, useRef, useState } from "react";
import { Plus, Search, SlidersHorizontal, LayoutGrid, List, Bookmark, Users, Pencil, Trash2, Folder, X } from "lucide-react";
import { Button } from "../ui/button";
import { Surface, Confirm } from "../ui/surface";
import { ProductCategoryMarker, Avatar, PlatformBadge, OpenProduct, EmptyState } from "../shared";
import { useWorkspace } from "../workspace-provider";
import { formatMoney } from "@/lib/domain/money";
import { platforms, platformLabels, type Platform } from "@/lib/domain/urls";
import { normalizeText } from "@/lib/domain/categories";
import { FavoriteEditor, type ClientFavorite } from "./favorite-editor";
import { CollectionEditor } from "./collections";
import type { ClientData } from "@/lib/domain/services";
const qcLabels = { not_reviewed: "Não avaliado", approved: "Aprovado", rejected: "Reprovado" };
export function FavoritesScreen() {
  const { data, busy, mutate } = useWorkspace(); const router = useRouter(), params = useSearchParams();
  const [tab, setTab] = useState<"all" | "mine">("all"), [search, setSearch] = useState(""), [person, setPerson] = useState(""), [platform, setPlatform] = useState(""), [qc, setQc] = useState(""), [price, setPrice] = useState(""), [filters, setFilters] = useState(false);
  const browserRef = useRef<HTMLDivElement>(null), optionRefs = useRef(new Map<string, HTMLButtonElement>());
  const [selection, setSelection] = useState<{ left: number; width: number } | null>(null);
  const [editor, setEditor] = useState<ClientFavorite | "new" | null>(null), [detail, setDetail] = useState<ClientFavorite | null>(null), [remove, setRemove] = useState(false);
  const [collectionEditor, setCollectionEditor] = useState<ClientData["collections"][number] | "new" | null>(null);
  const collectionId = params.get("collection") ?? "", queryNewCollection = params.get("newCollection") === "1";
  const collection = data.collections.find(c => c.id === collectionId);
  const activeFilters = [person, platform, qc, price, collectionId].filter(Boolean).length;
  const activeOption = person || tab;
  const results = data.favorites.filter(f => (tab !== "mine" || f.ownerId === data.currentUser.id) && (!person || f.ownerId === person) && (!platform || f.platform === platform) && (!qc || f.qcStatus === qc) && (!collectionId || (collectionId === "none" ? !f.collectionId : f.collectionId === collectionId)) && (!price || (price === "yes" ? f.priceCents !== null : f.priceCents === null)) && (!search || normalizeText([f.name, f.variant, f.notes].join(" ")).includes(normalizeText(search))));
  const otherMembers = data.members.filter(member => member.id !== data.currentUser.id);
  useLayoutEffect(() => {
    const updateSelection = () => {
      const selected = optionRefs.current.get(activeOption);
      if (selected) setSelection({ left: selected.offsetLeft, width: selected.offsetWidth });
    };
    updateSelection();
    window.addEventListener("resize", updateSelection);
    return () => window.removeEventListener("resize", updateSelection);
  }, [activeOption, otherMembers.length]);
  function chooseCollection(id: string) { router.replace(id ? `/favorites?collection=${encodeURIComponent(id)}` : "/favorites", { scroll: false }); }
  function closeCollection() { setCollectionEditor(null); if (queryNewCollection) router.replace("/favorites", { scroll: false }); }
  function addLink(f: ClientFavorite) { return `/purchase?favorite=${f.id}`; }
  return <><div className="page-heading"><div><h1>Favoritos</h1><p className="muted">Produtos salvos pelo grupo, organizados do seu jeito.</p></div><Button className="favorites-heading-add" onClick={() => setEditor("new")} aria-label="Novo favorito"><Plus size={19}/><span className="desktop-label">Novo favorito</span></Button></div>
  <Button className="favorites-mobile-add" onClick={() => setEditor("new")} aria-label="Novo favorito"><Plus size={24}/></Button>
  <div className="favorites-browser" ref={browserRef} role="group" aria-label="Filtrar favoritos por pessoa" style={{ "--selection-left": `${selection?.left ?? 0}px`, "--selection-width": `${selection?.width ?? 0}px` } as React.CSSProperties}>
    <span className={`favorite-selection${selection ? " ready" : ""}`} aria-hidden="true" />
    <div className="favorite-modes" role="group" aria-label="Favoritos">
      <button ref={element => { if (element) optionRefs.current.set("all", element); else optionRefs.current.delete("all"); }} type="button" className={`favorite-mode${activeOption === "all" ? " selected" : ""}`} aria-pressed={activeOption === "all"} onClick={() => { setTab("all"); setPerson(""); }}><Users size={17}/><span>Todos</span><small>{data.favorites.length}</small></button>
      <button ref={element => { if (element) optionRefs.current.set("mine", element); else optionRefs.current.delete("mine"); }} type="button" className={`favorite-mode${activeOption === "mine" ? " selected" : ""}`} aria-pressed={activeOption === "mine"} onClick={() => { setTab("mine"); setPerson(""); }}><Bookmark size={16}/><span>Meus</span><small>{data.favorites.filter(f => f.ownerId === data.currentUser.id).length}</small></button>
    </div>
    {otherMembers.map(member => {
    const count = data.favorites.filter(f => f.ownerId === member.id).length;
    const selected = person === member.id;
    return <button key={member.id} ref={element => { if (element) optionRefs.current.set(member.id, element); else optionRefs.current.delete(member.id); }} type="button" className={`favorite-person${selected ? " selected" : ""}${member.id === otherMembers[0]?.id ? " first-person-option" : ""}`} aria-pressed={selected} onClick={() => { setTab("all"); setPerson(selected ? "" : member.id); }}>
      <Avatar name={member.name}/><span className="favorite-person-copy"><strong>{member.name}</strong><span>{count} {count === 1 ? "favorito" : "favoritos"}</span></span>
    </button>;
  })}</div>
  <div className="favorites-toolbar"><div className="search-input"><Search size={19}/><input aria-label="Buscar favoritos" placeholder="Buscar favoritos…" value={search} onChange={e => setSearch(e.target.value)}/>{search && <Button size="icon" variant="ghost" aria-label="Limpar busca" onClick={() => setSearch("")}><X size={16}/></Button>}</div><Button variant={filters || activeFilters ? "soft" : "outline"} size="icon" aria-label="Filtros" aria-expanded={filters} onClick={() => setFilters(!filters)}><SlidersHorizontal size={19}/>{activeFilters > 0 && <span className="filter-count">{activeFilters}</span>}</Button><div className="view-toggle" aria-label="Visualização"><Button aria-label="Lista" aria-pressed={data.view === "list"} variant="ghost" size="icon" disabled={busy} onClick={() => mutate("preference.view", "list", undefined, "Visualização em lista")}><List size={19}/></Button><Button aria-label="Cards" aria-pressed={data.view === "cards"} variant="ghost" size="icon" disabled={busy} onClick={() => mutate("preference.view", "cards", undefined, "Visualização em cards")}><LayoutGrid size={19}/></Button></div></div>
  {filters && <div className="filter-panel"><label>Pessoa<select value={person} onChange={e => { setPerson(e.target.value); if (e.target.value) setTab("all"); }}><option value="">Todas as pessoas</option>{data.members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Plataforma<select value={platform} onChange={e => setPlatform(e.target.value)}><option value="">Todas as plataformas</option>{platforms.map(p => <option key={p} value={p}>{platformLabels[p]}</option>)}</select></label><label>Coleção<select value={collectionId} onChange={e => chooseCollection(e.target.value)}><option value="">Todas as coleções</option><option value="none">Sem coleção</option>{data.collections.map(c => <option key={c.id} value={c.id}>{c.name} · {data.members.find(m => m.id === c.ownerId)?.name}</option>)}</select></label><label>QC<select value={qc} onChange={e => setQc(e.target.value)}><option value="">Todas as avaliações</option>{Object.entries(qcLabels).map(([v, name]) => <option key={v} value={v}>{name}</option>)}</select></label><label>Preço<select value={price} onChange={e => setPrice(e.target.value)}><option value="">Todos</option><option value="yes">Com preço</option><option value="no">Sem preço</option></select></label><Button variant="ghost" onClick={() => { setPerson(""); setPlatform(""); setQc(""); setPrice(""); chooseCollection(""); }}>Limpar filtros</Button></div>}
  <div className="mobile-collections"><label>Coleção<select aria-label="Filtrar por coleção" value={collectionId} onChange={e => chooseCollection(e.target.value)}><option value="">Todas as coleções</option><option value="none">Sem coleção</option><optgroup label="Minhas coleções">{data.collections.filter(c => c.ownerId === data.currentUser.id).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</optgroup>{data.members.filter(m => m.id !== data.currentUser.id && data.collections.some(c => c.ownerId === m.id)).map(m => <optgroup key={m.id} label={`De ${m.name}`}>{data.collections.filter(c => c.ownerId === m.id).map(c => <option key={c.id} value={c.id}>{c.name} · {m.name}</option>)}</optgroup>)}</select></label><Button variant="outline" size="icon" aria-label="Nova coleção" onClick={() => setCollectionEditor("new")}><Plus size={18}/></Button></div>
  {collection && <div className="collection-heading"><h2><Folder size={18}/>{collection.name}</h2><span className="muted">{collection.ownerId === data.currentUser.id ? "Sua coleção" : `Coleção de ${data.members.find(m => m.id === collection.ownerId)?.name}`}</span>{collection.ownerId === data.currentUser.id && <Button size="sm" variant="ghost" onClick={() => setCollectionEditor(collection)}><Pencil size={14}/>Editar coleção</Button>}</div>}
  <div className={`favorites-content ${data.view}`} data-testid="favorites-content">{results.map(f => { const owner = data.members.find(m => m.id === f.ownerId)!; return <article key={f.id} className="favorite" data-testid="favorite"><ProductCategoryMarker visualKey={f.visualKey}/><div className="favorite-info"><button className="favorite-title" title={f.name} onClick={() => setDetail(f)}>{f.name}</button><p className="favorite-variant muted">{f.variant || "Sem variação"}</p><div className="favorite-price">{f.priceCents === null ? <span className="favorite-price-missing">Preço não informado</span> : formatMoney(f.priceCents)}</div><div className="favorite-meta"><span className={`owner ${f.ownerId === data.currentUser.id ? "owner-self" : ""}`}><Avatar name={owner.name}/><span>{f.ownerId === data.currentUser.id ? "Seu favorito" : `De ${owner.name}`}</span></span><PlatformBadge platform={f.platform}/></div></div><div className="favorite-actions"><OpenProduct url={f.url}/><Button asChild size="sm" variant="soft"><Link href={addLink(f)} aria-label={`Adicionar ${f.name} à compra`}><Plus size={16}/>Compra</Link></Button></div></article>; })}</div>
  {!results.length && <EmptyState icon={Bookmark} title={data.favorites.length ? "Nenhum favorito por aqui" : "Seu próximo achado começa aqui"} description={data.favorites.length ? "Ajuste a busca ou os filtros para encontrar o que procura." : "Salve um produto pelo link e compartilhe seus achados com o grupo."}>{!data.favorites.length && <Button onClick={() => setEditor("new")}><Plus size={18}/>Novo favorito</Button>}</EmptyState>}
  {editor && <FavoriteEditor key={editor === "new" ? "new" : editor.id} favorite={editor === "new" ? undefined : editor} onClose={() => setEditor(null)} onExisting={f => { setEditor(null); setDetail(f); }}/>} 
  {detail && <Surface sheet title="Detalhes do favorito" open onOpenChange={v => { if (!v) setDetail(null); }}><ProductCategoryMarker visualKey={detail.visualKey}/><div className="detail-heading"><h2>{detail.name}</h2><PlatformBadge platform={detail.platform}/></div><p className="muted">{detail.variant}</p><p className="detail-price">{detail.priceCents === null ? "Sem preço" : formatMoney(detail.priceCents)}</p><div className="detail-meta"><span className="owner"><Avatar name={data.members.find(m => m.id === detail.ownerId)?.name ?? ""}/>{data.members.find(m => m.id === detail.ownerId)?.name}</span><span className={`badge qc-${detail.qcStatus}`}>{qcLabels[detail.qcStatus]}</span></div>{detail.collectionId && <p className="muted">Coleção: {data.collections.find(c => c.id === detail.collectionId)?.name}</p>}{detail.notes && <div className="detail-notes"><h3>Notas</h3><p>{detail.notes}</p></div>}<div className="detail-actions"><OpenProduct url={detail.url}/><Button asChild variant="soft"><Link href={addLink(detail)}><Plus size={17}/>Adicionar à compra</Link></Button></div>{detail.ownerId === data.currentUser.id && <div className="detail-owner-actions"><Button variant="outline" onClick={() => { setEditor(detail); setDetail(null); }}><Pencil size={16}/>Editar favorito</Button><Button variant="ghost" className="danger-text" onClick={() => setRemove(true)}><Trash2 size={16}/>Excluir favorito</Button></div>}</Surface>}
  <Confirm open={remove} onOpenChange={setRemove} title="Excluir favorito?" description="Os itens já adicionados às compras continuam salvos." label="Excluir favorito" danger busy={busy} onConfirm={async () => { if (detail && await mutate("favorite.delete", undefined, detail.id, "Favorito excluído")) { setDetail(null); setRemove(false); } }}/>
  {(collectionEditor || queryNewCollection) && <CollectionEditor key={typeof collectionEditor === "object" && collectionEditor ? collectionEditor.id : "new"} collection={typeof collectionEditor === "object" && collectionEditor ? collectionEditor : undefined} onClose={closeCollection}/>} 
  <p className="result-count muted">{results.length} {results.length === 1 ? "favorito" : "favoritos"}{platform && ` · ${platformLabels[platform as Platform]}`}</p>
  </>;
}
