import { test, expect, type Page } from "@playwright/test";
import { login } from "./helpers";
const origin = "http://localhost:3100";
async function issue(page: Page, email: string) {
  const response = await page.request.post("/api/group", { headers: { Origin: origin }, data: { operation: "issue", email } });
  expect(response.status()).toBe(200);
  return (await response.json()).link as string;
}
test("member generates a link and a new mobile user joins the group", async ({ page, browser }) => {
  await login(page);
  await page.getByRole("link", { name: "Perfil", exact: true }).click();
  await page.getByRole("link", { name: "Meu grupo", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Meu grupo", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Convidar pessoa", exact: true }).click();
  await page.getByLabel("Email da pessoa").fill("new-invite@loti.test");
  await page.getByRole("button", { name: "Gerar link de convite", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("Convite pronto para compartilhar");
  const link = await page.getByLabel("Link de convite").inputValue();
  expect(link).toMatch(/^http:\/\/localhost:3100\/invite\/[A-Za-z0-9_-]{43}$/);
  await expect(page.getByRole("button", { name: "Copiar link", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Fechar", exact: true }).click();
  await expect(page.locator(".group-list li").filter({ hasText: "new-invite@loti.test" })).toBeVisible();
  await page.screenshot({ path: "artifacts/qa/group-desktop.png", fullPage: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const invited = await context.newPage();
  await invited.setExtraHTTPHeaders({ "X-Forwarded-For": "203.0.113.210" });
  await invited.goto(link);
  await expect(invited.getByRole("heading", { name: "Entre no grupo Loti" })).toBeVisible();
  await expect(invited.locator('meta[name="referrer"]')).toHaveAttribute("content", "no-referrer");
  await invited.getByLabel("Seu nome", { exact: true }).fill("Nova pessoa E2E");
  await invited.getByLabel("Senha", { exact: true }).fill("Invitation-E2E-2026!");
  await invited.getByLabel("Confirmar senha", { exact: true }).fill("Invitation-E2E-other!");
  await invited.getByRole("button", { name: "Criar conta e entrar no grupo" }).click();
  await expect(invited.getByRole("main").getByRole("alert")).toContainText("As senhas precisam ser iguais");
  await invited.getByLabel("Confirmar senha", { exact: true }).fill("Invitation-E2E-2026!");
  await invited.screenshot({ path: "artifacts/qa/invitation-mobile.png", fullPage: true });
  await invited.getByRole("button", { name: "Criar conta e entrar no grupo" }).click();
  await expect(invited).toHaveURL(/\/favorites$/);
  await invited.reload();
  const data = await (await invited.request.get("/api/app")).json();
  expect(data.currentUser.email).toBe("new-invite@loti.test");
  expect(data.favorites.length).toBeGreaterThan(0);
  await invited.goto("/group");
  await expect(invited.locator(".group-list li").filter({ hasText: "new-invite@loti.test" })).toBeVisible();
  expect(await invited.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await invited.screenshot({ path: "artifacts/qa/group-mobile.png", fullPage: true });
  await invited.goto(link);
  await expect(invited.getByRole("main").getByRole("alert")).toContainText("já foi usado");
  await context.close();
});
test("existing account switches from wrong session and returns from login to accept", async ({ page }) => {
  await login(page, "brunna");
  const link = await issue(page, "existing-invite@loti.test");
  await page.goto(link);
  await expect(page.getByText("Você está conectado como", { exact: false })).toBeVisible();
  const forbidden = await page.request.post(link.replace("/invite/", "/api/invitations/"), { headers: { Origin: origin }, data: {} });
  expect(forbidden.status()).toBe(403);
  await page.getByRole("button", { name: "Trocar de conta", exact: true }).click();
  await expect(page).toHaveURL(/\/login\?returnTo=/);
  await page.getByLabel("Email", { exact: true }).fill("existing-invite@loti.test");
  await page.getByLabel("Senha", { exact: true }).fill("Loti-Dev-Only-2026!");
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await expect(page).toHaveURL(link);
  await expect(page.getByRole("button", { name: "Aceitar convite", exact: true })).toBeVisible();
  await expect(page.getByLabel("Senha", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Aceitar convite", exact: true }).click();
  await expect(page).toHaveURL(/\/favorites$/);
  await page.goto("/profile");
  await page.getByRole("button", { name: "Sair da conta", exact: true }).click();
  await page.getByLabel("Email", { exact: true }).fill("existing-invite@loti.test");
  await page.getByLabel("Senha", { exact: true }).fill("Loti-Dev-Only-2026!");
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await expect(page).toHaveURL(/\/favorites$/);
});
test("regeneration invalidates old link and revocation invalidates replacement", async ({ page, browser }) => {
  await login(page, "amanda");
  const link = await issue(page, "revoked-invite@loti.test");
  await page.goto("/group");
  const row = page.locator(".group-list li").filter({ hasText: "revoked-invite@loti.test" });
  await row.getByRole("button", { name: "Gerar novo link", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Gerar novo link", exact: true }).click();
  const replacement = await page.getByLabel("Link de convite").inputValue();
  expect(replacement).not.toBe(link);
  await page.getByRole("button", { name: "Fechar", exact: true }).click();
  const visitorContext = await browser.newContext(), visitor = await visitorContext.newPage();
  await visitor.goto(link);
  await expect(visitor.getByRole("main").getByRole("alert")).toContainText("revogado");
  await row.getByRole("button", { name: "Revogar", exact: true }).click();
  await page.getByRole("button", { name: "Revogar convite", exact: true }).click();
  await expect(row).toHaveCount(0);
  await visitor.goto(replacement);
  await expect(visitor.getByRole("main").getByRole("alert")).toContainText("revogado");
  await visitorContext.close();
});
test("invitation APIs require membership and trusted origin; login cannot redirect externally", async ({ page, request }) => {
  expect((await request.get("/api/group")).status()).toBe(401);
  expect((await request.post("/api/group", { headers: { Origin: origin }, data: { operation: "issue", email: "no@loti.test" } })).status()).toBe(401);
  await login(page, "bola");
  expect((await page.request.post("/api/group", { headers: { Origin: "https://example.com" }, data: { operation: "issue", email: "no@loti.test" } })).status()).toBe(403);
  expect((await request.get("/api/invitations/invalid")).status()).toBe(404);
  await page.goto("/profile");
  await page.getByRole("button", { name: "Sair da conta", exact: true }).click();
  await page.goto("/login?returnTo=https%3A%2F%2Fexample.com");
  await page.getByLabel("Email", { exact: true }).fill("bola@loti.test");
  await page.getByLabel("Senha", { exact: true }).fill("Loti-Dev-Only-2026!");
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await expect(page).toHaveURL(/\/favorites$/);
});
test("session failure after acceptance recovers through normal login", async ({ page, browser }) => {
  await login(page, "vinicius");
  const link = await issue(page, "session-recovery@loti.test");
  const context = await browser.newContext(), invited = await context.newPage();
  await invited.setExtraHTTPHeaders({ "X-Forwarded-For": "203.0.113.211" });
  await invited.goto(link);
  await invited.getByLabel("Seu nome", { exact: true }).fill("Session recovery");
  await invited.getByLabel("Senha", { exact: true }).fill("Session-Recovery-2026!");
  await invited.getByLabel("Confirmar senha", { exact: true }).fill("Session-Recovery-2026!");
  await invited.route("**/api/auth/sign-in/email", route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ message: "Simulated session failure", code: "SERVICE_UNAVAILABLE" }) }));
  await invited.getByRole("button", { name: "Criar conta e entrar no grupo" }).click();
  await expect(invited.getByRole("main").getByRole("alert")).toContainText("Sua conta foi criada e você já faz parte do grupo");
  expect((await (await page.request.get("/api/group")).json()).members.some((m: { email: string }) => m.email === "session-recovery@loti.test")).toBe(true);
  await invited.unroute("**/api/auth/sign-in/email");
  await invited.getByRole("link", { name: "Entrar na minha conta", exact: true }).click();
  await invited.getByLabel("Email", { exact: true }).fill("session-recovery@loti.test");
  await invited.getByLabel("Senha", { exact: true }).fill("Session-Recovery-2026!");
  await invited.getByRole("button", { name: "Entrar", exact: true }).click();
  await expect(invited).toHaveURL(/\/favorites$/);
  await context.close();
});
