import { test, expect } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { login } from "./helpers";

test("finalized purchase gets a separate cost tracking with payment, package, and reopen flow", async ({ page }) => {
  const screenshotDir = resolve(process.cwd(), "artifacts/qa/packages-costs-ux");
  async function capture(name: string, fullPage = false) {
    if (process.env.LOTI_CAPTURE_PACKAGES_QA !== "1") return;
    mkdirSync(screenshotDir, { recursive: true });
    await page.screenshot({ path: join(screenshotDir, `${name}.png`), fullPage });
  }

  await login(page, "profile-qa", "Profile-QA-Old-2026!");
  const origin = "http://localhost:3100";
  const created = await page.request.post("/api/app", { headers: { Origin: origin }, data: { operation: "purchase.save", input: { name: "Custos QA outubro", hubbuyAccount: "hubbuy-qa@example.test" } } });
  expect(created.ok()).toBeTruthy();
  const purchaseData = await created.json();
  const purchase = purchaseData.result as { id: string };
  const memberId = purchaseData.data.currentUser.id as string;
  const added = await page.request.post("/api/app", { headers: { Origin: origin }, data: { operation: "item.save", input: { name: "Tênis de teste", url: "https://example.test/shoe", personId: memberId, quantity: 1, unitPriceCents: 10_000 } } });
  expect(added.ok()).toBeTruthy();
  const finalized = await page.request.post("/api/app", { headers: { Origin: origin }, data: { operation: "purchase.finalize", id: purchase.id, input: true } });
  expect(finalized.ok()).toBeTruthy();
  const list = await page.request.get("/api/packages");
  expect(list.ok()).toBeTruthy();
  const rows = (await list.json()).data as { tracking: { id: string }; purchase: { id: string } }[];
  const tracking = rows.find(row => row.purchase.id === purchase.id)!.tracking;

  await page.goto(`/packages/${tracking.id}`);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await expect(page.getByRole("heading", { name: "Custos QA outubro" })).toBeVisible();
  await expect(page.getByText("Conta HubBuy: hubbuy-qa@example.test")).toBeVisible();
  await capture("initial-1440");
  await page.setViewportSize({ width: 390, height: 844 });
  await capture("initial-390", false);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const productsSection = page.getByRole("button", { name: /Produtos e pagamento/ });
  await expect(productsSection).toHaveAttribute("aria-expanded", "false");
  await expect(page.getByRole("table")).toBeHidden();
  const packagesSection = page.locator(".cost-progressive-toggle").nth(1);
  await expect(packagesSection).toHaveAttribute("aria-expanded", "false");
  await packagesSection.click();
  await expect(page.locator(".cost-package-toggle")).toHaveAttribute("aria-expanded", "false");
  await packagesSection.click();
  await expect(page.getByRole("button", { name: /Divisão por pessoa/ })).toHaveAttribute("aria-expanded", "false");
  await page.getByRole("button", { name: /Informar frete China de Tênis/ }).click();
  await expect(page.locator(".cost-table").getByRole("button", { name: "Editar valores", exact: true })).toBeFocused();
  for (let column = 1; column <= 7; column++) await expect(page.locator(".cost-table thead th").nth(column)).toHaveCSS("text-align", "right");
  await capture("products-1440");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator(".cost-product-mobile-list")).toBeVisible();
  await expect(page.locator(".cost-table-wrap")).toBeHidden();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await capture("products-390", false);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator(".cost-table").getByRole("button", { name: "Ver composição", exact: true }).click();
  const composition = page.getByRole("dialog");
  await expect(composition.getByRole("heading", { name: "Composição · Tênis de teste" })).toBeVisible();
  await expect(composition.getByText("Preço efetivo", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(composition).toHaveCSS("opacity", "1");
  await capture("product-breakdown-390", false);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await composition.getByRole("button", { name: "Fechar" }).click();
  await expect(page.locator(".cost-table").getByRole("button", { name: "Ver composição", exact: true })).toBeFocused();
  await page.locator(".cost-table").getByRole("button", { name: "Editar valores", exact: true }).click();
  let dialog = page.getByRole("dialog");
  await dialog.getByLabel("Frete China por unidade").selectOption("known");
  await dialog.getByLabel("Valor em R$").nth(1).fill("10,00");
  await dialog.getByRole("button", { name: "Salvar custos", exact: true }).click();
  await page.locator(".cost-product-payment select").selectOption("pix");
  await page.getByRole("button", { name: "Marcar como pago", exact: true }).click();
  await page.locator(".cost-table").getByRole("button", { name: "Editar valores", exact: true }).click();
  dialog = page.getByRole("dialog");
  await dialog.getByLabel("Valor em R$").first().fill("101,00");
  await dialog.getByRole("button", { name: "Salvar custos", exact: true }).click();
  await page.getByRole("dialog").filter({ hasText: "Voltar pagamento para pendente?" }).getByRole("button", { name: "Salvar e invalidar pagamento", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Cancelar", exact: true }).click();
  await expect(page.getByRole("button", { name: "Marcar como pago", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Marcar como pago", exact: true }).click();
  await page.getByRole("button", { name: /Informar frete Brasil de Pacote 1/i }).click();
  await expect(page.locator(".cost-charge-summary").first().getByRole("button", { name: "Informar Frete Brasil", exact: true })).toBeFocused();
  await expect(page.locator(".cost-package-toggle")).toHaveAttribute("aria-expanded", "true");
  await page.getByText("Custos do produto atualizados", { exact: true }).waitFor({ state: "hidden" });
  await capture("package-open-1440");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator(".cost-package-toggle").evaluate(element => element.scrollIntoView({ block: "start" }));
  await capture("package-open-390", false);
  await expect(page.getByLabel("Tênis de teste neste pacote")).toBeHidden();
  await page.getByRole("button", { name: "Editar conteúdo", exact: true }).click();
  const contentEditor = page.getByRole("dialog");
  await contentEditor.getByLabel("Tênis de teste neste pacote").fill("0");
  await contentEditor.getByRole("button", { name: "Cancelar", exact: true }).click();
  await expect(page.locator(".cost-package-items")).toContainText("1 unidade");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator(".cost-charge-summary").nth(0).getByRole("button", { name: "Informar Frete Brasil", exact: true }).click();
  dialog = page.getByRole("dialog");
  await expect(dialog).toHaveCSS("opacity", "1");
  await capture("charge-form-1440", false);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(dialog).toHaveCSS("opacity", "1");
  await dialog.evaluate(element => { element.scrollTop = 0; });
  await capture("charge-form-390", false);
  await dialog.getByLabel("Estado do valor").selectOption("known");
  await dialog.getByLabel("Valor em R$").fill("25,00");
  await dialog.getByLabel("Método de pagamento").selectOption("pix");
  await dialog.getByRole("button", { name: "Salvar cobrança", exact: true }).click();
  await page.getByRole("button", { name: "Marcar como pago", exact: true }).click();
  await page.locator(".cost-charge-summary").nth(1).getByRole("button", { name: "Informar Receita", exact: true }).click();
  dialog = page.getByRole("dialog");
  await dialog.getByLabel("Estado do valor").selectOption("no_charge");
  await dialog.getByRole("button", { name: "Salvar cobrança", exact: true }).click();
  await page.getByRole("button", { name: "Encerrar custos", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Encerrar custos", exact: true }).click();
  await expect(page.getByText("Custos encerrados", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Reabrir acompanhamento", exact: true }).click();
  await page.getByLabel("Motivo").fill("Ajuste solicitado na revisão QA");
  await page.getByRole("button", { name: "Confirmar reabertura", exact: true }).click();
  await expect(page.getByText("Custos abertos", { exact: true })).toBeVisible();
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: width <= 390 ? 844 : 1000 });
    const dimensions = await page.evaluate(() => ({ viewport: window.innerWidth, content: document.documentElement.scrollWidth }));
    expect(dimensions.content, `Horizontal overflow at ${dimensions.viewport}px: ${dimensions.content}px`).toBeLessThanOrEqual(dimensions.viewport);
  }
  await expect(page.locator(".mobile-island a")).toHaveCount(4);
});
