import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { eq } from "drizzle-orm";
import { purchaseItems, purchases } from "@/lib/db/schema";
import { fixture, favorite } from "./helpers";
let f: ReturnType<typeof fixture>;
beforeEach(() => { f = fixture(); }); afterEach(() => f.sqlite.close());
const item = { name: "Manual", url: "https://example.com/product", personId: "bob", quantity: 2, unitPriceCents: 1000 };
function snapshot() { const p = f.alice.savePurchase({ name: "Compra teste" }); const fav = f.alice.saveFavorite(favorite); const saved = f.bob.addFavoriteToPurchase({ favoriteId: fav.id, personId: "alice", quantity: 3, unitPriceCents: 12500, variant: "42" }); return { p, fav, saved }; }
describe("purchase rules", () => {
  it("denies a second active purchase in service and database", () => { f.alice.savePurchase({ name: "First" }); expect(() => f.bob.savePurchase({ name: "Second" })).toThrow("ativa"); expect(() => f.db.insert(purchases).values({ id: "second", workspaceId: "workspace", name: "Second", createdBy: "bob", createdAt: new Date(), status: "active" }).run()).toThrow(/UNIQUE/); });
  it("rejects purchase writes from outsiders", () => { const p = f.alice.savePurchase({ name: "First" }); expect(() => f.outsider.savePurchase({ name: "changed" }, p.id)).toThrow(); expect(() => f.foreign.finalizePurchase(p.id, true)).toThrow(); });
  it("copies favorite snapshots and records creator and target separately", () => { const { saved } = snapshot(); expect(saved.name).toBe(favorite.name); expect(saved.url).toBe(favorite.url); expect(saved.createdBy).toBe("bob"); expect(saved.personId).toBe("alice"); expect(saved.quantity).toBe(3); });
  it("editing favorite never alters snapshot", () => { const { saved, fav } = snapshot(); f.alice.saveFavorite({ ...favorite, name: "changed", priceCents: 1, variant: "different" }, fav.id); const stored = f.db.select().from(purchaseItems).where(eq(purchaseItems.id, saved.id)).get()!; expect(stored.name).toBe(favorite.name); expect(stored.unitPriceCents).toBe(12500); expect(stored.variant).toBe("42"); });
  it("deleting source favorite preserves finalized item", () => { const { p, saved, fav } = snapshot(); f.alice.finalizePurchase(p.id, true); f.alice.deleteFavorite(fav.id); const stored = f.db.select().from(purchaseItems).where(eq(purchaseItems.id, saved.id)).get()!; expect(stored.sourceFavoriteId).toBeNull(); expect(stored.name).toBe(favorite.name); expect(stored.url).toBe(favorite.url); });
  it("any member edits active items without changing favorite", () => { const { saved, fav } = snapshot(); f.alice.saveManualItem({ ...item, name: "new snapshot" }, saved.id); expect(f.bob.getData().items[0].name).toBe("new snapshot"); expect(f.bob.getData().favorites.find(x => x.id === fav.id)?.name).toBe(favorite.name); });
  it("manual items do not create favorites", () => { f.alice.savePurchase({ name: "Manual" }); f.bob.saveManualItem(item); expect(f.alice.getData().favorites).toHaveLength(0); });
  it("does not merge duplicate rows", () => { f.alice.savePurchase({ name: "Manual" }); f.alice.saveManualItem(item); f.alice.saveManualItem(item); expect(f.alice.getData().items).toHaveLength(2); });
  it("requires target membership", () => { f.alice.savePurchase({ name: "Manual" }); expect(() => f.alice.saveManualItem({ ...item, personId: "outsider" })).toThrow(); expect(() => f.alice.saveManualItem({ ...item, personId: "foreign" })).toThrow(); });
  it.each([0, -1, 1.5])("rejects quantity %s at server and SQLite boundaries", quantity => { const { saved } = snapshot(); expect(() => f.alice.saveManualItem({ ...item, quantity }, saved.id)).toThrow(); expect(() => f.db.update(purchaseItems).set({ quantity }).where(eq(purchaseItems.id, saved.id)).run()).toThrow(); });
  it.each([-1, 1.1])("rejects price %s at both boundaries", unitPriceCents => { const { saved } = snapshot(); expect(() => f.alice.saveManualItem({ ...item, unitPriceCents }, saved.id)).toThrow(); expect(() => f.db.update(purchaseItems).set({ unitPriceCents }).where(eq(purchaseItems.id, saved.id)).run()).toThrow(); });
  it("keeps null prices and toggles status", () => { f.alice.savePurchase({ name: "Manual" }); const saved = f.alice.saveManualItem({ ...item, unitPriceCents: null }); expect(saved.unitPriceCents).toBeNull(); f.bob.setCartStatus(saved.id, "added"); expect(f.alice.getData().items[0].cartStatus).toBe("added"); });
  it("requires explicit confirmation but allows pending/no-price finalization", () => { const { p } = snapshot(); f.alice.saveManualItem({ ...item, unitPriceCents: null }); expect(() => f.bob.finalizePurchase(p.id, false)).toThrow("Confirme"); f.bob.finalizePurchase(p.id, true); expect(f.alice.getData().purchases[0].status).toBe("finalized"); });
  it("rejects all finalized mutations and allows a next purchase", () => { const { p, saved } = snapshot(); f.alice.finalizePurchase(p.id, true); const mutations = [() => f.bob.savePurchase({ name: "changed" }, p.id), () => f.bob.saveManualItem(item, saved.id), () => f.bob.removePurchaseItem(saved.id), () => f.bob.setCartStatus(saved.id, "added"), () => f.bob.finalizePurchase(p.id, true)]; for (const mutate of mutations) expect(mutate).toThrow("finalizada"); expect(() => f.bob.saveManualItem(item)).toThrow(); const next = f.bob.savePurchase({ name: "Next" }); expect(next.status).toBe("active"); });
  it("rejects cross-workspace item access", () => { const { saved } = snapshot(); expect(() => f.foreign.removePurchaseItem(saved.id)).toThrow(); });
});
