"use client";
import { useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import Link from "next/link";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { Plus, ShoppingCart, MoreHorizontal, Check, Pencil, Trash2, LockKeyhole, ArrowLeft, AlertTriangle } from "lucide-react";
import { Button } from "../ui/button";
import { Confirm, Surface } from "../ui/surface";
import { Avatar, ProductVisual, OpenProduct, EmptyState, PlatformBadge } from "../shared";
import { useWorkspace } from "../workspace-provider";
import { formatMoney, purchaseSummary, personSummary, subtotal } from "@/lib/domain/money";
import { PurchaseEditor } from "./purchase-editor";
import { AddItemFlow, ItemEditor, type ClientItem } from "./item-editor";
import type { ClientData } from "@/lib/domain/services";
export function PurchaseScreen() {
  const { data } = useWorkspace(); const params = useSearchParams(); const [create, setCreate] = useState(false);
  const purchase = data.purchases.find(p => p.status === "active");
  if (purchase) return <PurchaseView key={purchase.id} purchase={purchase}/>;
  return <><div className="page-heading"><div><h1>Compra atual</h1><p className="muted">O próximo pedido começa com seus favoritos.</p></div></div><EmptyState icon={ShoppingCart} title="Vamos comprar juntos?" description="Crie uma compra para reunir os itens de todo mundo e acompanhar o que já entrou no carrinho HubBuy."><Button onClick={() => setCreate(true)}><Plus size={18}/>Criar compra</Button>{params.get("favorite") && <p className="muted">Depois de criar a compra, você pode adicionar o favorito selecionado.</p>}</EmptyState>{create && <PurchaseEditor onClose={() => setCreate(false)}/>}</>;
}
export function PurchaseView({ purchase }: { purchase: ClientData["purchases"][number] }) {
  const { data, busy, mutate } = useWorkspace(), params = useSearchParams(), router = useRouter();
  const [filter, setFilter] = useState("all"), [person, setPerson] = useState(""), [add, setAdd] = useState(false), [metadata, setMetadata] = useState(false), [finalize, setFinalize] = useState(false), [edit, setEdit] = useState<ClientItem | null>(null), [remove, setRemove] = useState<ClientItem | null>(null), [detail, setDetail] = useState<ClientItem | null>(null);
  const readonly = purchase.status === "finalized", items = data.items.filter(i => i.purchaseId === purchase.id), summary = purchaseSummary(items);
  const favorite = !readonly ? data.favorites.find(f => f.id === params.get("favorite")) : undefined;
  const people = data.members.filter(m => items.some(i => i.personId === m.id));
  const filtered = items.filter(i => (!person || i.personId === person) && (filter === "all" || i.cartStatus === filter));
  function closeAdd() { setAdd(false); if (params.get("favorite")) router.replace("/purchase", { scroll: false }); }
  return <>{readonly && <Link href="/history" className="back-link"><ArrowLeft size={16}/>Histórico</Link>}<div className="page-heading purchase-heading"><div><div className="purchase-title"><h1>{purchase.name}</h1><span className={`badge purchase-status ${readonly ? "finalized" : ""}`}>{readonly ? <LockKeyhole size={12}/> : <span className="status-dot"/>}{readonly ? "Finalizada" : "Em andamento"}</span></div><p className="muted">{summary.units} {summary.units === 1 ? "unidade" : "unidades"} · {summary.people} {summary.people === 1 ? "pessoa" : "pessoas"}{purchase.hubbuyAccount && <span> · Conta HubBuy: {purchase.hubbuyAccount}</span>}{readonly && purchase.finalizedAt && <span> · {new Date(purchase.finalizedAt).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" })}</span>}</p></div>{!readonly && <DropdownMenu.Root><DropdownMenu.Trigger asChild><Button variant="outline" size="icon" aria-label="Opções da compra"><MoreHorizontal size={20}/></Button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="dropdown" align="end" sideOffset={8}><DropdownMenu.Item onSelect={() => setMetadata(true)}><Pencil size={15}/>Editar compra</DropdownMenu.Item><DropdownMenu.Item onSelect={() => setFinalize(true)}><Check size={15}/>Finalizar compra</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>}</div>
  <div className="purchase-summary"><div className="progress-panel"><div className="progress-label"><strong>{summary.added} de {summary.units} adicionadas</strong><span>{summary.progress}%</span></div><div className="progress-track" role="progressbar" aria-label="Itens adicionados ao carrinho" aria-valuemin={0} aria-valuemax={100} aria-valuenow={summary.progress}><span style={{ width: `${summary.progress}%` }}/></div></div><div className="total-panel"><span className="muted">Valor total (estimado)</span><strong data-testid="purchase-total">{formatMoney(summary.totalCents)}</strong>{summary.noPriceRows > 0 && <small>{summary.noPriceUnits} {summary.noPriceUnits === 1 ? "unidade sem preço" : "unidades sem preço"}</small>}</div></div>
  <div className="purchase-toolbar"><div className="segmented purchase-tabs"><button className={filter === "all" ? "selected" : ""} onClick={() => setFilter("all")}>Todos <span>{summary.units}</span></button><button className={filter === "pending" ? "selected" : ""} onClick={() => setFilter("pending")}>Pendentes <span>{summary.pending}</span></button><button className={filter === "added" ? "selected" : ""} onClick={() => setFilter("added")}>Adicionados <span>{summary.added}</span></button></div>{!readonly && <Button onClick={() => setAdd(true)} aria-label="Adicionar item"><Plus size={18}/><span className="desktop-label">Adicionar item</span></Button>}</div>
  {!!people.length && <div className="person-strip">{people.map(m => { const s = personSummary(items, m.id); return <button className={`person-summary ${person === m.id ? "selected" : ""}`} key={m.id} onClick={() => setPerson(person === m.id ? "" : m.id)} aria-pressed={person === m.id}><Avatar name={m.name}/><span><strong>{m.name}</strong><small>{s.units} {s.units === 1 ? "unidade" : "unidades"} · {s.added}/{s.units} adicionadas</small><b>{formatMoney(s.totalCents)}</b></span></button>; })}</div>}
  {data.members.filter(m => filtered.some(i => i.personId === m.id)).map(m => { const group = filtered.filter(i => i.personId === m.id), s = personSummary(items, m.id); return <section className="purchase-group" key={m.id}><div className="group-heading"><Avatar name={m.name}/><div><h2>{m.name}</h2><p className="muted">{s.units} {s.units === 1 ? "unidade" : "unidades"} · {formatMoney(s.totalCents)} · {s.added}/{s.units} adicionadas</p></div></div><div className="table-head"><span>Produto</span><span>Qtd × Preço unitário</span><span>Subtotal</span></div>{group.map(i => <article className="purchase-row" key={i.id} data-testid="purchase-item">{readonly ? <span className={`cart-readonly ${i.cartStatus}`} aria-label={i.cartStatus === "added" ? "Adicionado" : "Pendente"}>{i.cartStatus === "added" ? <Check size={16}/> : <span/>}</span> : <button className={`cart-toggle ${i.cartStatus}`} aria-pressed={i.cartStatus === "added"} aria-label={`Marcar ${i.name} como ${i.cartStatus === "added" ? "pendente" : "adicionado"}`} disabled={busy} onClick={() => mutate("item.status", i.cartStatus === "added" ? "pending" : "added", i.id, i.cartStatus === "added" ? "Marcado como pendente" : "Marcado como adicionado")}>{i.cartStatus === "added" && <Check size={16}/>}</button>}<ProductVisual visualKey={i.visualKey}/><div className="purchase-item-info"><button className="favorite-title" onClick={() => setDetail(i)}>{i.name}</button><p className="muted">{i.variant || "Sem variação"}</p><span className="mobile-item-price">{i.quantity} × {formatMoney(i.unitPriceCents)}</span></div><span className="item-unit-price">{i.quantity} × {formatMoney(i.unitPriceCents)}</span><strong className={`item-subtotal ${i.unitPriceCents === null ? "price-pending" : ""}`}>{formatMoney(subtotal(i))}</strong><div className="purchase-row-actions"><OpenProduct url={i.url} compact/><span className="cart-text">{i.cartStatus === "added" ? "Adicionado" : "Pendente"}</span>{!readonly && <DropdownMenu.Root><DropdownMenu.Trigger asChild><Button variant="ghost" size="icon" aria-label={`Opções de ${i.name}`}><MoreHorizontal size={18}/></Button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="dropdown" align="end" sideOffset={5}><DropdownMenu.Item onSelect={() => setEdit(i)}><Pencil size={15}/>Editar item</DropdownMenu.Item><DropdownMenu.Item className="danger-text" onSelect={() => setRemove(i)}><Trash2 size={15}/>Remover item</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>}</div></article>)}</section>; })}
  {!filtered.length && <EmptyState icon={ShoppingCart} title={items.length ? "Tudo certo por aqui" : "A compra ainda está vazia"} description={items.length ? "Nenhum item com estes filtros. Selecione Todos para ver a compra completa." : "Adicione um favorito ou um item manual para começar."}>{!items.length && !readonly && <Button variant="soft" onClick={() => setAdd(true)}><Plus size={18}/>Adicionar item</Button>}</EmptyState>}
  {!readonly && items.length > 0 && <div className="finalize-footer"><p className="muted">Terminou esta rodada?</p><Button variant="outline" onClick={() => setFinalize(true)}><Check size={16}/>Finalizar compra</Button></div>}
  {(add || favorite) && !readonly && <AddItemFlow key={favorite?.id ?? "new"} initialFavorite={favorite} onClose={closeAdd}/>} {edit && !readonly && <ItemEditor key={edit.id} item={edit} onClose={() => setEdit(null)}/>} {metadata && !readonly && <PurchaseEditor purchase={purchase} onClose={() => setMetadata(false)}/>}
  <Confirm open={!!remove && !readonly} onOpenChange={v => { if (!v) setRemove(null); }} title="Remover item?" description="O favorito de origem continua salvo." danger label="Remover item" busy={busy} onConfirm={async () => { if (remove && await mutate("item.delete", undefined, remove.id, "Item removido")) setRemove(null); }}/>
  <Confirm open={finalize && !readonly} onOpenChange={setFinalize} title="Finalizar esta compra?" description="A compra vai para o histórico e não poderá ser alterada." label="Confirmar finalização" busy={busy} onConfirm={async () => { if (await mutate("purchase.finalize", true, purchase.id, "Compra finalizada")) { setFinalize(false); router.push(`/history/${purchase.id}`); } }}>{(summary.pending > 0 || summary.noPriceRows > 0) && <div className="finalize-warning"><AlertTriangle size={18}/><div>{summary.pending > 0 && <p>{summary.pending} unidades ainda pendentes.</p>}{summary.noPriceRows > 0 && <p>{summary.noPriceUnits} unidades estão sem preço.</p>}<p>Você pode finalizar mesmo assim.</p></div></div>}</Confirm>
  {detail && <Surface sheet title={readonly ? "Item do histórico" : "Detalhes do item"} open onOpenChange={v => { if (!v) setDetail(null); }}><ProductVisual visualKey={detail.visualKey} large/><div className="detail-heading"><h2>{detail.name}</h2><PlatformBadge platform={detail.platform}/></div><p className="muted">{detail.variant}</p><p className="detail-price">{formatMoney(subtotal(detail))}</p><p className="muted">{detail.quantity} × {formatMoney(detail.unitPriceCents)} · {data.members.find(m => m.id === detail.personId)?.name}</p><p className="muted">{detail.cartStatus === "added" ? "Adicionado ao carrinho" : "Pendente"}</p>{detail.notes && <div className="detail-notes"><h3>Notas</h3><p>{detail.notes}</p></div>}<div className="detail-actions"><OpenProduct url={detail.url}/>{!readonly && <Button variant="outline" onClick={() => { setEdit(detail); setDetail(null); }}><Pencil size={16}/>Editar item</Button>}</div>{readonly && <p className="readonly-notice"><LockKeyhole size={14}/>Registro somente leitura</p>}</Surface>}
  </>;
}
